export const  DataPackages = [
    {
        h3 : "Basic",
        span :"$",
        h1 :"29",
        p : "per user,per month",
        button : "Start Basic",
        i1: "fa-solid fa-circle-check",
        h41 : "99.5% Uptime Guarantee",
        i2: "fa-solid fa-circle-check",
        h42 : "120Gb CDN Bandwidth",
        i3: "fa-solid fa-circle-check",
        h43 : "5GB Cloud Storage",
        i4: "fa-solid fa-circle-xmark",
        h44 : "Personal Help Support",
        i5: "fa-solid fa-circle-xmark",
        h45 : "Enterprise SLA",
    },
    {
        h3 : "Standard",
        span :"$",
        h1 :"49",
        p : "per user,per month",
        button : "Start Standard",
        i1 : "fa-solid fa-circle-check",
        h41 : "99.5% Uptime Guarantee",
        i2 : "fa-solid fa-circle-check",
        h42 : "150Gb CDN Bandwidth",
        i3 : "fa-solid fa-circle-check",
        h43 : "10GB Cloud Storage",
        i4 : "fa-solid fa-circle-check",
        h44 : "Personal Help Support",
        i5 : "fa-solid fa-circle-xmark",
        h45 : "Enterprise SLA",
    },
    {
        h3 : "Platinum",
        span :"$",
        h1 :"79",
        p : "2 user,per month",
        button : "Start Platinum",
        i1 : "fa-solid fa-circle-check",
        h41 : "99.5% Uptime Guarantee",
        i2 : "fa-solid fa-circle-check",
        h42 : "120Gb CDN Bandwidth",
        i3 : "fa-solid fa-circle-check",
        h43 : "20GB Cloud Storage",
        i4 : "fa-solid fa-circle-check",
        h44 : "Personal Help Support",
        i5 : "fa-solid fa-circle-check",
        h45 : "Enterprise SLA",
    },
]